name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: npm ci
    - name: Compile NPM
      run: npm run build
    - name: Compile sbt
      run: sbt compile
    - name: Run core tests
      run: sbt coreJVM/test
    - name: Run frontend tests
      run: sbt frontend/test
    - name: Run backend tests
      env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
      run: sbt backend/test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - name: build frontend
        run: |
          npm ci
          npm run build
      - name: build service worker
        run: sbt service-worker/stage
      - name: build backend
        run: sbt backend/stage
      - name: login docker hub
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: build docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/nutria .
      - name: publish docker image
        if: github.ref == 'refs/heads/master'
        run: docker push ${{secrets.DOCKER_USER}}/nutria
